### ISSUE TITLE
tshark crashes on packet length of 0

### ISSUE THREAD

**Issue by oemki** [emericv/ZenaNG#4]
I have the problem that frequently tshark was crashed and the returning SIGPIPE signal as well  stops the zenang process. I found out that the reason is a zero length package. I fixed that and will upload my fix. Please verify and commit the change if correct

**Comment by emericv** [comment]
OK, thanks for the contribution.
In fact, I thinks that a packet cannot be 0 byte length too...
I will integrate this fix.

It may be more judicious to add a test with the minimum 802.15.4 MAC frame length but I don't remember it...

**Comment by emericv** [comment]
Fixed by #5
